return {
	"xiyaowong/transparent.nvim",
	config = function()
		require("transparent").setup({
			groups = {
				"Normal",
				"NormalNC",
				"Comment",
				"Constant",
				"Special",
				"Identifier",
				"Statement",
				"PreProc",
				"Type",
				"Underlined",
				"Todo",
				"String",
				"Function",
				"Conditional",
				"Repeat",
				"Operator",
				"Structure",
				"LineNr",
				"NonText",
				"SignColumn",
				"CursorLine",
				"CursorLineNr",
				"StatusLine",
				"StatusLineNC",
				"EndOfBuffer",
        "NeoTreeNormal",
        "NeoTreeNormalNC",
			},
			extra_groups = {
				"NvimTree",
				"NvimTreeNormal",
				"NvimTreeVertSplit",
				"NvimTreeStatusLine",
				"NvimTreeStatusLineNC",
				"LuaLine",
			},
			exclude_groups = {},
		})
    vim.keymap.set("n", "<leader>tt", ":TransparentToggle<CR>", {})
	end,
}
